#!/bin/bash -
#
#echo "ARGS: $@"
#while true
##do
#	echo $RANDOM
#	sleep 1
#done

PS4='$ '

export PATH=/bin:/usr/bin:/usr/local/bin:$GOPATH/bin:$HOME/bin

export GOPATH=$HOME/project
mkdir -p $GOPATH/{src,bin}
export GOBIN=$GOPATH/bin

test -d $GOPATH || mkdir -p $GOPATH


addr=$1
case "$addr" in
	github.com/*)
		addr="https://$addr"
		;;
	git.oschina.net/*)
		addr="http://$addr"
		;;
esac

path=${1%.git}
path=${path#https://}
path=${path#http://}

cd "$GOPATH/src"
if test -d "$path"
then
	cd "${path}"
	set -eu -x # open debug
	git pull </dev/null|| exit 2
else
	TIMEOUT=30s
	echo "git clone: timeout $TIMEOUT"
	#timeout $TIMEOUT 
	set -eu -x # open debug
	git clone "$addr" "${path}" || exit 1
	cd "${path}"
fi
	
export GOBIN="$GOBIN/${path//\//-}"


go get -v
go test -short
go install

echo $GOBIN/${path##*/}
